[package]
name = "tcpimpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun = "0.5.5"
anyhow = "1"
etherparse = "0.13"
